// vue/src/App.vue
<script setup>
import { onMounted, onUnmounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute()
const menuOpen = ref(false)

function closeMenu() {
  menuOpen.value = false
}

function toggleMenu() {
  menuOpen.value = !menuOpen.value
}

watch(
  () => route.fullPath,
  () => {
    closeMenu()
  }
)

function onKeydown(event) {
  if (event.key === 'Escape') closeMenu()
}

onMounted(() => {
  window.addEventListener('keydown', onKeydown)
})

onUnmounted(() => {
  window.removeEventListener('keydown', onKeydown)
})
</script>

<template>
  <div class="app-shell">
    <header class="site-nav">
      <div class="site-nav-inner">
        <RouterLink class="brand" to="/" @click="closeMenu">JobFinder</RouterLink>

        <button
          type="button"
          class="nav-toggle"
          :aria-expanded="menuOpen ? 'true' : 'false'"
          aria-controls="site-nav-links"
          @click="toggleMenu"
        >
          <span class="sr-only">{{ menuOpen ? 'Close menu' : 'Open menu' }}</span>
          <span class="nav-toggle-bars" aria-hidden="true" />
        </button>

        <nav
          id="site-nav-links"
          class="nav-links"
          :class="{ open: menuOpen }"
          aria-label="Primary"
        >
          <RouterLink
            to="/"
            class="nav-link"
            :class="{ active: route.name === 'all-jobs' }"
          >
            All Jobs
          </RouterLink>
          <RouterLink
            to="/hr"
            class="nav-link"
            :class="{ active: route.name === 'hr-jobs' }"
          >
            HR Jobs
          </RouterLink>
        </nav>
      </div>
    </header>

    <main class="app-main">
      <RouterView :key="route.fullPath" />
    </main>

    <footer class="site-footer">
      <a
        class="powered-by"
        href="https://getjobbox.com"
        target="_blank"
        rel="noopener noreferrer"
      >
        <span class="powered-by-label">Powered by</span>
        <img
          class="powered-by-logo"
          src="/brand/icon.webp"
          alt="JobBox"
          width="28"
          height="28"
        />
        <span class="powered-by-name">JobBox</span>
      </a>
    </footer>
  </div>
</template>

// angular/src/app/app.component.ts
import { Component, DestroyRef, HostListener, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { NavigationEnd, Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { filter } from 'rxjs';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  templateUrl: './app.component.html',
  styles: `:host { display: block; }`,
})
export class AppComponent {
  private readonly router = inject(Router);
  private readonly destroyRef = inject(DestroyRef);

  readonly menuOpen = signal(false);

  constructor() {
    this.router.events
      .pipe(
        filter((event) => event instanceof NavigationEnd),
        takeUntilDestroyed(this.destroyRef)
      )
      .subscribe(() => this.closeMenu());
  }

  closeMenu(): void {
    this.menuOpen.set(false);
  }

  toggleMenu(): void {
    this.menuOpen.update((open) => !open);
  }

  @HostListener('document:keydown', ['$event'])
  onKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      this.closeMenu();
    }
  }
}

<div class="app-shell">
  <header class="site-nav">
    <div class="site-nav-inner">
      <a class="brand" routerLink="/" (click)="closeMenu()">JobFinder</a>

      <button
        type="button"
        class="nav-toggle"
        [attr.aria-expanded]="menuOpen() ? 'true' : 'false'"
        aria-controls="site-nav-links"
        (click)="toggleMenu()"
      >
        <span class="sr-only">{{ menuOpen() ? 'Close menu' : 'Open menu' }}</span>
        <span class="nav-toggle-bars" aria-hidden="true"></span>
      </button>

      <nav
        id="site-nav-links"
        class="nav-links"
        [class.open]="menuOpen()"
        aria-label="Primary"
      >
        <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }" class="nav-link" (click)="closeMenu()">
          All Jobs
        </a>
        <a routerLink="/hr" routerLinkActive="active" class="nav-link" (click)="closeMenu()">
          HR Jobs
        </a>
      </nav>
    </div>
  </header>

  <main class="app-main">
    <router-outlet />
  </main>

  <footer class="site-footer">
    <a
      class="powered-by"
      href="https://getjobbox.com"
      target="_blank"
      rel="noopener noreferrer"
    >
      <span class="powered-by-label">Powered by</span>
      <img
        class="powered-by-logo"
        src="/brand/icon.webp"
        alt="JobBox"
        width="28"
        height="28"
      />
      <span class="powered-by-name">JobBox</span>
    </a>
  </footer>
</div>
