// vue/src/components/Pagination.vue
<script setup>
import { computed } from 'vue'

const props = defineProps({
  currentPage: { type: Number, required: true },
  totalItems: { type: Number, required: true },
  itemsPerPage: { type: Number, required: true },
  loading: { type: Boolean, default: false },
})

const emit = defineEmits(['update:page'])

const totalPages = computed(() => Math.max(1, Math.ceil(props.totalItems / props.itemsPerPage)))

const startItem = computed(() => {
  if (props.totalItems === 0) return 0
  return (props.currentPage - 1) * props.itemsPerPage + 1
})

const endItem = computed(() => {
  if (props.totalItems === 0) return 0
  return Math.min(props.currentPage * props.itemsPerPage, props.totalItems)
})

const maxVisiblePages = 5
const halfVisible = Math.floor(maxVisiblePages / 2)

const visiblePages = computed(() => {
  if (totalPages.value <= maxVisiblePages) {
    return Array.from({ length: totalPages.value }, (_, i) => i + 1)
  }

  let start = Math.max(1, props.currentPage - halfVisible)
  let end = Math.min(totalPages.value, start + maxVisiblePages - 1)

  if (end === totalPages.value) {
    start = Math.max(1, end - maxVisiblePages + 1)
  }

  return Array.from({ length: end - start + 1 }, (_, i) => start + i)
})

const showFirstPage = computed(
  () => totalPages.value > maxVisiblePages && visiblePages.value[0] > 1
)

const showLastPage = computed(
  () =>
    totalPages.value > maxVisiblePages &&
    visiblePages.value[visiblePages.value.length - 1] < totalPages.value
)

const showStartEllipsis = computed(
  () => totalPages.value > maxVisiblePages && visiblePages.value[0] > 2
)

const showEndEllipsis = computed(
  () =>
    totalPages.value > maxVisiblePages &&
    visiblePages.value[visiblePages.value.length - 1] < totalPages.value - 1
)

function goToPage(page) {
  if (props.loading) return
  const next = Math.max(1, Math.min(totalPages.value, page))
  if (next === props.currentPage) return
  emit('update:page', next)
  window.scrollTo({ top: 0, behavior: 'smooth' })
}
</script>

<template>
  <div v-if="totalItems > 0" class="pager">
    <p class="pager-summary">
      Showing {{ startItem }} to {{ endItem }} of {{ totalItems.toLocaleString() }} results
    </p>

    <div v-if="totalPages > 1" class="pager-controls">
      <button
        type="button"
        class="pager-btn"
        :disabled="loading || currentPage <= 1"
        @click="goToPage(currentPage - 1)"
      >
        Previous
      </button>

      <div class="pager-pages">
        <button
          v-if="showFirstPage"
          type="button"
          class="pager-num"
          :disabled="loading"
          @click="goToPage(1)"
        >
          1
        </button>
        <span v-if="showStartEllipsis" class="pager-ellipsis">…</span>

        <button
          v-for="page in visiblePages"
          :key="page"
          type="button"
          class="pager-num"
          :class="{ active: page === currentPage }"
          :disabled="loading"
          @click="goToPage(page)"
        >
          {{ page }}
        </button>

        <span v-if="showEndEllipsis" class="pager-ellipsis">…</span>
        <button
          v-if="showLastPage"
          type="button"
          class="pager-num"
          :disabled="loading"
          @click="goToPage(totalPages)"
        >
          {{ totalPages }}
        </button>
      </div>

      <button
        type="button"
        class="pager-btn"
        :disabled="loading || currentPage >= totalPages"
        @click="goToPage(currentPage + 1)"
      >
        Next
      </button>
    </div>
  </div>
</template>

// react/src/components/Pagination.jsx
import { useMemo } from 'react'

const MAX_VISIBLE_PAGES = 5
const HALF_VISIBLE = Math.floor(MAX_VISIBLE_PAGES / 2)

export default function Pagination({
  currentPage,
  totalItems,
  itemsPerPage,
  loading = false,
  onPageChange,
}) {
  const totalPages = Math.max(1, Math.ceil(totalItems / itemsPerPage))

  const startItem = totalItems === 0 ? 0 : (currentPage - 1) * itemsPerPage + 1
  const endItem =
    totalItems === 0 ? 0 : Math.min(currentPage * itemsPerPage, totalItems)

  const visiblePages = useMemo(() => {
    if (totalPages <= MAX_VISIBLE_PAGES) {
      return Array.from({ length: totalPages }, (_, i) => i + 1)
    }
    let start = Math.max(1, currentPage - HALF_VISIBLE)
    let end = Math.min(totalPages, start + MAX_VISIBLE_PAGES - 1)
    if (end === totalPages) {
      start = Math.max(1, end - MAX_VISIBLE_PAGES + 1)
    }
    return Array.from({ length: end - start + 1 }, (_, i) => start + i)
  }, [currentPage, totalPages])

  const showFirstPage = totalPages > MAX_VISIBLE_PAGES && visiblePages[0] > 1
  const showLastPage =
    totalPages > MAX_VISIBLE_PAGES &&
    visiblePages[visiblePages.length - 1] < totalPages
  const showStartEllipsis = totalPages > MAX_VISIBLE_PAGES && visiblePages[0] > 2
  const showEndEllipsis =
    totalPages > MAX_VISIBLE_PAGES &&
    visiblePages[visiblePages.length - 1] < totalPages - 1

  function goToPage(page) {
    if (loading) return
    const next = Math.max(1, Math.min(totalPages, page))
    if (next === currentPage) return
    onPageChange?.(next)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  if (totalItems <= 0) return null

  return (
    <div className="pager">
      <p className="pager-summary">
        Showing {startItem} to {endItem} of {totalItems.toLocaleString()} results
      </p>

      {totalPages > 1 ? (
        <div className="pager-controls">
          <button
            type="button"
            className="pager-btn"
            disabled={loading || currentPage <= 1}
            onClick={() => goToPage(currentPage - 1)}
          >
            Previous
          </button>

          <div className="pager-pages">
            {showFirstPage ? (
              <button
                type="button"
                className="pager-num"
                disabled={loading}
                onClick={() => goToPage(1)}
              >
                1
              </button>
            ) : null}
            {showStartEllipsis ? <span className="pager-ellipsis">…</span> : null}

            {visiblePages.map((page) => (
              <button
                key={page}
                type="button"
                className={`pager-num${page === currentPage ? ' active' : ''}`}
                disabled={loading}
                onClick={() => goToPage(page)}
              >
                {page}
              </button>
            ))}

            {showEndEllipsis ? <span className="pager-ellipsis">…</span> : null}
            {showLastPage ? (
              <button
                type="button"
                className="pager-num"
                disabled={loading}
                onClick={() => goToPage(totalPages)}
              >
                {totalPages}
              </button>
            ) : null}
          </div>

          <button
            type="button"
            className="pager-btn"
            disabled={loading || currentPage >= totalPages}
            onClick={() => goToPage(currentPage + 1)}
          >
            Next
          </button>
        </div>
      ) : null}
    </div>
  )
}
