// angular/src/app/shared/components/pagination/pagination.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';

const MAX_VISIBLE_PAGES = 5;
const HALF_VISIBLE = Math.floor(MAX_VISIBLE_PAGES / 2);

@Component({
  selector: 'app-pagination',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (totalItems() > 0) {
      <div class="pager">
        <p class="pager-summary">
          Showing {{ startItem() }} to {{ endItem() }} of
          {{ totalItems().toLocaleString() }} results
        </p>

        @if (totalPages() > 1) {
          <div class="pager-controls">
            <button
              type="button"
              class="pager-btn"
              [disabled]="loading() || currentPage() <= 1"
              (click)="goToPage(currentPage() - 1)"
            >
              Previous
            </button>

            <div class="pager-pages">
              @if (showFirstPage()) {
                <button
                  type="button"
                  class="pager-num"
                  [disabled]="loading()"
                  (click)="goToPage(1)"
                >
                  1
                </button>
              }
              @if (showStartEllipsis()) {
                <span class="pager-ellipsis">…</span>
              }

              @for (page of visiblePages(); track page) {
                <button
                  type="button"
                  class="pager-num"
                  [class.active]="page === currentPage()"
                  [disabled]="loading()"
                  (click)="goToPage(page)"
                >
                  {{ page }}
                </button>
              }

              @if (showEndEllipsis()) {
                <span class="pager-ellipsis">…</span>
              }
              @if (showLastPage()) {
                <button
                  type="button"
                  class="pager-num"
                  [disabled]="loading()"
                  (click)="goToPage(totalPages())"
                >
                  {{ totalPages() }}
                </button>
              }
            </div>

            <button
              type="button"
              class="pager-btn"
              [disabled]="loading() || currentPage() >= totalPages()"
              (click)="goToPage(currentPage() + 1)"
            >
              Next
            </button>
          </div>
        }
      </div>
    }
  `,
})
export class PaginationComponent {
  readonly currentPage = input.required<number>();
  readonly totalItems = input.required<number>();
  readonly itemsPerPage = input.required<number>();
  readonly loading = input(false);

  readonly pageChange = output<number>();

  readonly totalPages = computed(() =>
    Math.max(1, Math.ceil(this.totalItems() / this.itemsPerPage()))
  );

  readonly startItem = computed(() => {
    if (this.totalItems() === 0) return 0;
    return (this.currentPage() - 1) * this.itemsPerPage() + 1;
  });

  readonly endItem = computed(() => {
    if (this.totalItems() === 0) return 0;
    return Math.min(this.currentPage() * this.itemsPerPage(), this.totalItems());
  });

  readonly visiblePages = computed(() => {
    const total = this.totalPages();
    const current = this.currentPage();
    if (total <= MAX_VISIBLE_PAGES) {
      return Array.from({ length: total }, (_, i) => i + 1);
    }
    let start = Math.max(1, current - HALF_VISIBLE);
    let end = Math.min(total, start + MAX_VISIBLE_PAGES - 1);
    if (end === total) {
      start = Math.max(1, end - MAX_VISIBLE_PAGES + 1);
    }
    return Array.from({ length: end - start + 1 }, (_, i) => start + i);
  });

  readonly showFirstPage = computed(
    () => this.totalPages() > MAX_VISIBLE_PAGES && (this.visiblePages()[0] ?? 0) > 1
  );

  readonly showLastPage = computed(() => {
    const pages = this.visiblePages();
    const last = pages[pages.length - 1] ?? 0;
    return this.totalPages() > MAX_VISIBLE_PAGES && last < this.totalPages();
  });

  readonly showStartEllipsis = computed(
    () => this.totalPages() > MAX_VISIBLE_PAGES && (this.visiblePages()[0] ?? 0) > 2
  );

  readonly showEndEllipsis = computed(() => {
    const pages = this.visiblePages();
    const last = pages[pages.length - 1] ?? 0;
    return this.totalPages() > MAX_VISIBLE_PAGES && last < this.totalPages() - 1;
  });

  goToPage(page: number): void {
    if (this.loading()) return;
    const next = Math.max(1, Math.min(this.totalPages(), page));
    if (next === this.currentPage()) return;
    this.pageChange.emit(next);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
}

// react/src/components/Pagination.jsx
import { useMemo } from 'react'

const MAX_VISIBLE_PAGES = 5
const HALF_VISIBLE = Math.floor(MAX_VISIBLE_PAGES / 2)

export default function Pagination({
  currentPage,
  totalItems,
  itemsPerPage,
  loading = false,
  onPageChange,
}) {
  const totalPages = Math.max(1, Math.ceil(totalItems / itemsPerPage))

  const startItem = totalItems === 0 ? 0 : (currentPage - 1) * itemsPerPage + 1
  const endItem =
    totalItems === 0 ? 0 : Math.min(currentPage * itemsPerPage, totalItems)

  const visiblePages = useMemo(() => {
    if (totalPages <= MAX_VISIBLE_PAGES) {
      return Array.from({ length: totalPages }, (_, i) => i + 1)
    }
    let start = Math.max(1, currentPage - HALF_VISIBLE)
    let end = Math.min(totalPages, start + MAX_VISIBLE_PAGES - 1)
    if (end === totalPages) {
      start = Math.max(1, end - MAX_VISIBLE_PAGES + 1)
    }
    return Array.from({ length: end - start + 1 }, (_, i) => start + i)
  }, [currentPage, totalPages])

  const showFirstPage = totalPages > MAX_VISIBLE_PAGES && visiblePages[0] > 1
  const showLastPage =
    totalPages > MAX_VISIBLE_PAGES &&
    visiblePages[visiblePages.length - 1] < totalPages
  const showStartEllipsis = totalPages > MAX_VISIBLE_PAGES && visiblePages[0] > 2
  const showEndEllipsis =
    totalPages > MAX_VISIBLE_PAGES &&
    visiblePages[visiblePages.length - 1] < totalPages - 1

  function goToPage(page) {
    if (loading) return
    const next = Math.max(1, Math.min(totalPages, page))
    if (next === currentPage) return
    onPageChange?.(next)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  if (totalItems <= 0) return null

  return (
    <div className="pager">
      <p className="pager-summary">
        Showing {startItem} to {endItem} of {totalItems.toLocaleString()} results
      </p>

      {totalPages > 1 ? (
        <div className="pager-controls">
          <button
            type="button"
            className="pager-btn"
            disabled={loading || currentPage <= 1}
            onClick={() => goToPage(currentPage - 1)}
          >
            Previous
          </button>

          <div className="pager-pages">
            {showFirstPage ? (
              <button
                type="button"
                className="pager-num"
                disabled={loading}
                onClick={() => goToPage(1)}
              >
                1
              </button>
            ) : null}
            {showStartEllipsis ? <span className="pager-ellipsis">…</span> : null}

            {visiblePages.map((page) => (
              <button
                key={page}
                type="button"
                className={`pager-num${page === currentPage ? ' active' : ''}`}
                disabled={loading}
                onClick={() => goToPage(page)}
              >
                {page}
              </button>
            ))}

            {showEndEllipsis ? <span className="pager-ellipsis">…</span> : null}
            {showLastPage ? (
              <button
                type="button"
                className="pager-num"
                disabled={loading}
                onClick={() => goToPage(totalPages)}
              >
                {totalPages}
              </button>
            ) : null}
          </div>

          <button
            type="button"
            className="pager-btn"
            disabled={loading || currentPage >= totalPages}
            onClick={() => goToPage(currentPage + 1)}
          >
            Next
          </button>
        </div>
      ) : null}
    </div>
  )
}
